# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Squad AI (Windows + macOS Apple Silicon).

Build from the project root:

    pip install pyinstaller
    pyinstaller packaging/squad_ai.spec

Heavy optional packages (PaddleOCR, sentence-transformers, FAISS) are bundled
only if they are installed in the build environment; otherwise the produced app
simply runs without those features (graceful degradation). Downloaded ML models
are NOT bundled — they are fetched to the user cache dir on first use (see
packaging/MODELS.md).
"""
import os
import sys

from PyInstaller.utils.hooks import collect_all

block_cipher = None

# Icon files live next to this spec (packaging/). Generated by make_icon.py.
_ICON_DIR = SPECPATH  # PyInstaller sets SPECPATH to the spec's directory
_ICO = os.path.join(_ICON_DIR, "AppIcon.ico")
_ICNS = os.path.join(_ICON_DIR, "AppIcon.icns")
_PNG = os.path.join(_ICON_DIR, "AppIcon.png")

datas, binaries, hiddenimports = [], [], []
# Ship the PNG inside the app so the running window/taskbar can set its icon.
if os.path.exists(_PNG):
    datas.append((_PNG, "."))

# Bundle optional deps when present; skip silently when not installed.
# rapidocr_onnxruntime + onnxruntime ship the OCR models/binaries that make
# screenshot OCR work in the packaged app with no external install; cv2/shapely/
# pyclipper are its runtime deps.
for _pkg in ("paddleocr", "paddle", "sentence_transformers", "faiss",
             "rapidfuzz", "keyring", "pynput", "mss",
             "rapidocr_onnxruntime", "onnxruntime", "cv2", "shapely",
             "pyclipper"):
    try:
        d, b, h = collect_all(_pkg)
        datas += d
        binaries += b
        hiddenimports += h
    except Exception:  # noqa: BLE001
        pass

a = Analysis(
    ["../run.py"],
    pathex=[".."],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports + ["app"],
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter"],
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name="SquadAI",
    debug=False,
    strip=False,
    upx=True,
    console=False,  # windowed GUI app
    icon=(_ICO if os.path.exists(_ICO) else None),  # taskbar / .exe icon
)
coll = COLLECT(
    exe, a.binaries, a.datas,
    strip=False, upx=True, name="SquadAI",
)

# macOS: also produce a .app bundle (Apple Silicon when built on arm64).
if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="Squad AI.app",
        icon=(_ICNS if os.path.exists(_ICNS) else None),
        bundle_identifier="com.squadai.desktop",
        info_plist={
            "CFBundleName": "Squad AI",
            "CFBundleDisplayName": "Squad AI",
            "NSHighResolutionCapable": True,
            # Screen Recording permission prompt text for region capture.
            "NSCameraUsageDescription": "Not used.",
        },
    )
